modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "legendcontrol"
version = "${project_version}"
displayName = "${project_name} [Pixelmon]"
logoFile = "logo.png"
authors = "Vecoo"
description = "Addon changes spawn system for legendary pokemon."

[[mixins]]
config = "legendcontrol.mixins.json"

[[dependencies.legendcontrol]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legendcontrol]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legendcontrol]]
modId = "pixelmon"
type = "required"
versionRange = "[9.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legendcontrol]]
modId = "extralib"
type = "required"
versionRange = "[2.1.1,)"
ordering = "NONE"
side = "BOTH"