modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "legendcontrol_defender"
version = "${project_version}"
displayName = "${project_name}-Defender [Pixelmon]"
logoFile = "logo.png"
authors = "Vecoo"
description = "Addon changes spawn system for legendary pokemon."

[[dependencies.legendcontrol_defender]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legendcontrol_defender]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legendcontrol_defender]]
modId = "pixelmon"
type = "required"
versionRange = "[9.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legendcontrol_defender]]
modId = "extralib"
type = "required"
versionRange = "[2.1.1,)"
ordering = "NONE"
side = "BOTH"